as yet unclassified
drawArea

	self setForegroundColor: 12.
	buffer fillRectangle: gc x: p1 x value rounded - 20 y: 160 width: 40 height: 40.
	buffer fillRectangle: gc x: p2 x value rounded - 20 y: 160 width: 40 height: 40.
	buffer fillRectangle: gc x: p3 x value rounded - 20 y: 160 width: 40 height: 40.
	buffer fillRectangle: gc x: p4 x value rounded - 20 y: 160 width: 40 height: 40.
	buffer fillRectangle: gc x: p5 x value rounded - 20 y: 160 width: 40 height: 40